import { Avatar, Head } from "@components/Common";
import MainLayout from "@components/MainLayout";
import { createServerApi } from "@lib/API";
import { useUser } from "@lib/hooks";
import { GSSPC, GSSPR, PageProps } from "@lib/index";
import styles from "./about.module.scss";
import clsx from "clsx";
import authorStyles from "@components/ReleasePage/Sidebar/Authors.module.scss";

export default function AboutPage() {
  return (
    <MainLayout className={styles.container}>
      <Head
        path="/about"
        title="About RogueLibs"
        description="RogueLibs is a mod-sharing platform dedicated to enhancing gaming experiences for players of all levels. Our platform offers a community-centered approach to modding, where mod enthusiasts can collaborate, discuss new features, and share user-generated content seamlessly."
      />
      <div className={styles.header}>{"About RogueLibs"}</div>
      <div className={styles.description}>
        <p>
          {`RogueLibs is a mod-sharing platform dedicated to enhancing gaming experiences for players of all levels. Our platform offers a community-centered approach to modding, where mod enthusiasts can collaborate, discuss new features, and share user-generated content seamlessly.`}
        </p>
        <p>
          {`We pride ourselves in providing a safe, inclusive, and supportive environment for our users, where creativity and innovation reign. Whether you're looking to customize your gameplay or add new features to your favorite games, RogueLibs has got you covered.`}
        </p>
        <p>
          {`At RogueLibs, we're committed to fostering a culture of exploration and experimentation, allowing modders to push the limits of creative expression and realize their visions for the gaming industry's future.`}
        </p>
        <p>
          {`Join us today and become part of this vibrant, dynamic community of mod enthusiasts from around the world!`}
        </p>
        <span className={styles.footnote}>{"Generated by ChatGPT"}</span>
      </div>

      <div className={styles.header}>{"Contributors"}</div>
      <div className={styles.credits}>
        <Author user_id="4ce33253-ca26-4924-bfdc-8ed3ed9bd6e1" credit={"Developer of the library and the site."} />
        <Author user_id="4788ae9f-448f-4326-87f0-78244b56376d" credit={"RogueLibs logo and website icon design."} />
      </div>
    </MainLayout>
  );
}

export async function getServerSideProps(cxt: GSSPC): Promise<GSSPR<PageProps>> {
  const api = createServerApi(cxt);
  const session = await api.getSupabaseSession();

  return {
    props: {
      initialState: { session },
    },
  };
}

export type AuthorProps = {
  user_id: string;
  credit: string;
};
export function Author({ user_id, credit }: AuthorProps) {
  const user = useUser(user_id)[0];

  return (
    <div className={authorStyles.author}>
      <Avatar src={user?.avatar_url} href={`/user/${user?.slug ?? user?.id}`} />

      <div className={clsx(authorStyles.userInfo, credit && authorStyles.withCredits)}>
        <span className={authorStyles.username}>{user?.username ?? "..."}</span>
        {credit && (
          <div className={authorStyles.credits}>
            {credit.split("\n").map((line, i) => (
              <p key={i}>{line}</p>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
